#!/bin/bash

# Multi-Window Detection Test Script
# This script helps test the multi-window detection and refresh functionality

echo "🧪 Multi-Window Detection Test"
echo "=============================="
echo ""
echo "This test will help you verify that the admin panel properly detects"
echo "multiple windows and refreshes data when switching between them."
echo ""
echo "📋 Test Steps:"
echo "1. Open the admin panel in one browser window/tab"
echo "2. Open the admin panel in a second browser window/tab"
echo "3. Make changes in the first window (create/edit a link)"
echo "4. Switch to the second window"
echo "5. Wait 30+ seconds, then switch back to the first window"
echo "6. Look for the 'Refreshing...' badge in the header"
echo ""
echo "🔍 What to Look For:"
echo "• Console logs showing 'Multiple windows detected'"
echo "• Console logs showing 'Window focused after X ms - refreshing data'"
echo "• 'Refreshing...' badge appears in the header"
echo "• Data updates automatically without manual refresh"
echo ""
echo "🌐 Admin Panel URL: https://go.monumental-i.com/admin"
echo ""
echo "💡 Tips:"
echo "• Open browser dev tools (F12) to see console logs"
echo "• Try creating a new link in one window and see it appear in the other"
echo "• Test with different browsers (Chrome, Firefox, Safari)"
echo "• Test with incognito/private windows"
echo ""
echo "✅ Expected Behavior:"
echo "• Data stays synchronized between windows"
echo "• Automatic refresh when switching windows after 30+ seconds"
echo "• Visual feedback during refresh operations"
echo "• No manual refresh needed"
